version: "3.7"

networks:
  spendmanagement:
    external:
      name: spendmanagement-network

services:
    spendmanagement_readmodel:
      container_name: spendmanagement_readmodel
      build:
        context: .
        dockerfile: Dockerfile
      image: spendmanagement_readmodel
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
      ports:
        - "8080:80"
      networks:
        - spendmanagement      
