version: "3.7"

networks:
  spendmanagement-network:
    external: true

services:
    spendmanagement_readmodel:
      container_name: spendmanagement_readmodel
      build:
        context: .
        dockerfile: Dockerfile
      image: spendmanagement_readmodel:${APP_VERSION}
      environment:
        - APP_VERSION=${APP_VERSION}
        - ASPNETCORE_ENVIRONMENT=Development
      ports:
        - "9563:8080"
      networks:
        - spendmanagement      
