name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore src/Receipts.ReadModel.API/Receipts.ReadModel.API.csproj
    - name: Build
      run: dotnet build --no-restore --configuration Release src/Receipts.ReadModel.API/Receipts.ReadModel.API.csproj

  unit-tests:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Run unit tests
      run: dotnet test --no-build --verbosity normal tests/SpendManagament.ReadModel.UnitTests/SpendManagement.ReadModel.UnitTests.csproj
