name: .NET
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  VERSION_UPDATE_TYPE: "value"
  
jobs:
  
  bump:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    name: Build and bump version
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Determinar Tipo de Mudança
        id: determine_change_type
        run: |
          LAST_COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          if echo "$LAST_COMMIT_MESSAGE" | grep -qiE "feat"; then
            echo "VERSION_UPDATE_TYPE=MINOR" >> $GITHUB_ENV
          fi
          if echo "$LAST_COMMIT_MESSAGE" | grep -qiE "fix"; then
            echo "VERSION_UPDATE_TYPE=REVISION" >> $GITHUB_ENV
          fi

      - name: Print Update type
        run: |
          echo "Tipo de Mudança: $VERSION_UPDATE_TYPE"

      - name: Bump build version - Minor
        if: env.VERSION_UPDATE_TYPE == 'MINOR'
        id: bump-minor
        uses: vers-one/dotnet-project-version-updater@v1.5
        with:
          file: src/Receipts.QueryHandler.Api/Receipts.QueryHandler.Api.csproj
          version: "*.^.0"

      - name: Bump build version - Revision
        if: env.VERSION_UPDATE_TYPE == 'REVISION'
        id: bump-revision
        uses: vers-one/dotnet-project-version-updater@v1.5
        with:
          file: src/Receipts.QueryHandler.Api/Receipts.QueryHandler.Api.csproj
          version: "*.*.^"
          
      - name: Commit and push changes - MINOR
        if: env.VERSION_UPDATE_TYPE == 'MINOR'
        run: |
          git config user.name "Build - Incrementing version | Github action"
          git config user.email "deploy@spendmanagement.com"
          git add .
          git commit -m "CI: Updating application version ${{ steps.bump-minor.outputs.newVersion }}"
          git push
          echo "${{ steps.bump-minor.outputs.newVersion }}" > csproj_version.txt

      - name: Commit and push changes - Minor
        if: env.VERSION_UPDATE_TYPE == 'REVISION'
        run: |
          git config user.name "Build - Incrementing version | Github action"
          git config user.email "deploy@spendmanagement.com"
          git add .
          git commit -m "CI: Updating application version ${{ steps.bump-revision.outputs.newVersion }}"
          git push
          echo "${{ steps.bump-revision.outputs.newVersion }}" > csproj_version.txt

      - name: Store CSProj Version

          
  publish-docker-image:
    runs-on: ubuntu-latest
    needs: [bump]
    if: github.ref == 'refs/heads/main'
    steps:      
      - name: Read CSProj Version
        id: read_csproj_version
        run: | 
          echo "::set-output name=csproj_version::$(cat csproj_version.txt)"
          echo "The csproj version is $csproj_version"
               
