name: .NET
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


  
jobs:
  
  bump:
    runs-on: ubuntu-latest
    #needs: [build,unit-tests, integration-tests]
    outputs:
      version: ${{ steps.set-version.outputs.VERSION }}
      version_update_type: ${{ steps.determine_change_type.outputs.VERSION_UPDATE_TYPE }}
      
    if: github.ref == 'refs/heads/main'
    name: Build and bump version
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Determinar Tipo de Mudança
        id: determine_change_type
        run: |
          LAST_COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          if echo "$LAST_COMMIT_MESSAGE" | grep -qiE "feat"; then
            echo "VERSION_UPDATE_TYPE=MINOR" >> $GITHUB_OUTPUT
          fi
          if echo "$LAST_COMMIT_MESSAGE" | grep -qiE "fix"; then
            echo "VERSION_UPDATE_TYPE=REVISION" >> $GITHUB_OUTPUT
          fi

      - name: Print Update type
        run: |
          echo "Tipo de Mudança: $VERSION_UPDATE_TYPE"

      - name: Bump build version - Minor
        if: ${{ steps.determine_change_type.outputs.VERSION_UPDATE_TYPE }} == 'MINOR'
        id: bump-minor
        uses: vers-one/dotnet-project-version-updater@v1.5
        with:
          file: src/Receipts.QueryHandler.Api/Receipts.QueryHandler.Api.csproj
          version: "*.^.0"

      - name: Bump build version - Revision
        if: ${{ steps.determine_change_type.outputs.VERSION_UPDATE_TYPE }}== 'REVISION'
        id: bump-revision
        uses: vers-one/dotnet-project-version-updater@v1.5
        with:
          file: src/Receipts.QueryHandler.Api/Receipts.QueryHandler.Api.csproj
          version: "*.*.^"
          
      - name: Commit and push changes - MINOR
        if: env.VERSION_UPDATE_TYPE == 'MINOR'
        run: |
          git config user.name "Build - Incrementing version | Github action"
          git config user.email "deploy@spendmanagement.com"
          git add .
          git commit -m "CI: Updating application version ${{ steps.bump-minor.outputs.newVersion }}"
          git push

      - name: Commit and push changes - Revision
        if: env.VERSION_UPDATE_TYPE == 'REVISION'
        run: |
          git config user.name "Build - Incrementing version | Github action"
          git config user.email "deploy@spendmanagement.com"
          git add .
          git commit -m "CI: Updating application version ${{ steps.bump-minor.outputs.newVersion }}${{ steps.bump-revision.outputs.newVersion }}"
          git push

      - name: Set version - Revision
        id: set-version
        run: |
          if [[ ${{ env.VERSION_UPDATE_TYPE }} == 'REVISION' ]]; then
            echo "VERSION=${{ steps.bump-revision.outputs.newVersion }}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=${{ steps.bump-minor.outputs.newVersion }}" >> $GITHUB_OUTPUT
          fi
         
  publish-docker-image:
    needs: [bump]
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ needs.bump.outputs.version }}
    steps:      
      - name: Get csproj version
        id: get_version
        run: |                    
          echo "The csproj version is $VERSION"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Display appsettings before
        run: cat src/Receipts.QueryHandler.Api/appsettings.Development.json

      - name: Change connection string
        run: |
          sed -i 's/localhost:27017/mongodb:27017/g' src/Receipts.QueryHandler.Api/appsettings.Development.json
        working-directory: ${{ github.workspace }}

      - name: Display appsettings after changes
        run: cat src/Receipts.QueryHandler.Api/appsettings.Development.json
        
      - name: Build Docker image
        run: docker build -t "fmattioli/spendmanagement-receipts-queryhandler-api:$VERSION" .
  
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
  
      - name: Push Docker image to Docker Hub
        run: |
            docker push "fmattioli/spendmanagement-receipts-queryhandler-api:$VERSION"
            docker tag "fmattioli/spendmanagement-receipts-queryhandler-api:$VERSION" "fmattioli/spendmanagement-receipts-queryhandler-api:latest"
            docker push "fmattioli/spendmanagement-receipts-queryhandler-api:latest"
      
   
